# NumPy 

Numpy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use NumPy arrays than lists, check out this [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Using NumPy

Once you've installed NumPy, you can import it as a library.

In [57]:
import numpy as np

## Numpy Arrays

NumPy arrays are the main way we will use NumPy throughout the course. They essentially come in two flavours: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you note that one matrix can still have only one row and one column).

Let's begin our introduction by exploring how to create NumPy arrays.

### Creating NumPy Arrays

#### From a Python List

In [58]:
# creating a list
my_list = [1, 2, 3]

# print the list
print(my_list)

[1, 2, 3]


In [59]:
# Convert a list into a numPy array
array = np.array(my_list)

# Print the numpy array
print(array)

[1 2 3]


In [60]:
# Creating a list of lists
my_matrix = [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]

# Print the list of lists
print(my_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [61]:
# Convert a list of lists into a numPy array
my_mat = np.array(my_matrix)

# Print the 2D numPy array
print(my_mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


This is how we can cast a normal python list or a list of lists to corresponding numPy array but most often we'll be using numPy's built-in generation methods to create arrays a lot faster and simpler.

#### Using Built-in methods

There are a lot of different ways of creating numPy arrays using its built-in methods

###  arange()

Returns values separated by a given step size over the specified interval

In [62]:
np.arange(start=0, stop=10, step=1) # default step size = 2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### zeros and ones 

Generates arrays filled with either zeros or ones

In [63]:
# Pass in a number to create a 1D array filled with the specified number of zeros
np.zeros(3)

array([0., 0., 0.])

In [64]:
# Pass in a tuple representing the dimensions of the zero-filled matrix you would like to generate
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [65]:
# Pass in a number to create a 1D array filled with the specified number of ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [66]:
# Pass in a tuple representing the dimensions of the ones-filled matric you would like to generate
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace

Returns evenly spaced numbers over a provided range. The essential difference between NumPy linspace and NumPy arange is that linspace enables you to control the precise end value, whereas arange gives you more direct control over the increments between values in the sequence

In [67]:
# This generates 10 evenly spaced points over the specified range (0 and 5)
np.linspace(start=0, stop=5, num=10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [68]:
# This generates 100 evenly spaced points over the specified range (0 and 5)
np.linspace(start=0, stop=5, num=100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

### eye

Returns an identity matrix of the specified size/order

In [69]:
# Creating an identity matrix of order 4
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Generating Random Numbers

There are a lot of ways of producing Random numbers using NumPy

### rand

Returns an array of the given shape you pass in and populates it with a random sample of uniform distribution between 0 and 1

In [70]:
np.random.rand(5)

array([0.45650494, 0.23940295, 0.8372036 , 0.0178893 , 0.10576433])

In [71]:
# The dimensions of the np array has to be just numbers and not a tuple
np.random.rand(5, 5)

array([[0.27039897, 0.54677042, 0.5939058 , 0.62267571, 0.45810379],
       [0.54841575, 0.5302153 , 0.22317263, 0.09018142, 0.68823783],
       [0.28287999, 0.22375112, 0.51518053, 0.73129736, 0.43217039],
       [0.65442223, 0.32148441, 0.23764015, 0.8772595 , 0.5511263 ],
       [0.47537744, 0.29958536, 0.67739412, 0.66840503, 0.53814833]])

### randn 

Returns an array of the given shape you pass in and populates it with a random sample of standard normal distribution centred around 0.

In [72]:
np.random.randn(2)

array([-1.13104361,  0.84688478])

In [73]:
# The dimensions of the np array has to be just numbers and not a tuple
np.random.randn(5, 5)

array([[ 1.57689857, -0.53564082,  1.36490827,  1.29182037, -0.47280236],
       [-0.99357194,  0.50469215,  1.33771899,  0.07176908,  0.89391421],
       [ 0.68555333, -0.1826753 ,  0.17701504, -0.41716153, -0.35527282],
       [-0.10707736, -0.53950324,  0.00991997,  1.96625872, -1.16995747],
       [-0.12666384,  1.56255955,  1.06854274,  0.97637126, -1.99471552]])

### randint

Returns an array of random integers from a low to a high number (i.e. within a specified range)

In [74]:
# Provides 1 random integer between 1 (inclusive) and 100 (exclusive)
np.random.randint(low=1, high=100)

52

In [75]:
# Provides 10 random integers between 1 (inclusive) and 100 (exclusive)
np.random.randint(low=1, high=100, size=10)

array([18, 13, 92, 30, 39, 47, 79, 64,  9, 77])

### Arrays Methods

Let us discuss some useful attributes and method on an array 

In [76]:
# create a numPy array with integers from 0 (inclusive) to 25 (exclusive)
arr = np.arange(25)

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [77]:
# create a numPy array with 10 integers from 0 (inclusive) to 50 (exclusive)
random_arr = np.random.randint(low=0, high=50, size=10)

# print the array containing random values
print(random_arr)

[ 6 24 39 41  0 34 45 37 11 48]


### Reshape 

Returns an array containing the same data but with a different shape (dimensions)

In [78]:
# Pass in the dimensions of the shape as the parameters. (Not in a tuple format)
arr.reshape(5, 5) 

# Note that the number of elements in the matrix have to be the same as the product of the dimensions of the new shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

These are useful methods for finding max or min values or find their index locations using argmin or argmax

In [79]:
# Let us have a look at the array of random value that we have created
print(random_arr)

[ 6 24 39 41  0 34 45 37 11 48]


In [80]:
# To find the maximum value in the array, we use the max() method on it
print(random_arr.max())

48


In [81]:
# To find the minimum value in the array, we use the min() method on it
print(random_arr.min())

0


In [82]:
# To find the location (index) at which the max value is located in the array, we use the argmax() on it
print(random_arr.argmax())

9


In [83]:
# To find the location (index) at which the min value is located in the array, we use the argmin() on it
print(random_arr.argmin())

4


### Array Attributes 

### Shape

Shape is an attribute that an array has not a method. It returns the dimensions (shape) of the array.

In [84]:
# print the shape (dimensions) of the array
arr.shape

(25,)

In [85]:
# print the shape (dimensions) of the array
random_arr.shape

(10,)

In [86]:
# reshape the arr using the reshape() method
# Notice the set of 2 brackets
arr = arr.reshape(5, 5)

# print the reshaped array
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [87]:
# print the shape of the reshaped array
arr.shape

(5, 5)

### dtype 

Returns the data type of the object in the array

In [88]:
arr.dtype

dtype('int32')